2023-11-16 22:59:41,759 - INFO - Chosen prompt: Phantasmagoric scenes in the style of Zdzis\u0142aw Beksi\u0144ski, psychedelic twist, dark yet vibrant, ultra HD
        0: (purple:1.5), (mellow:1.8)
        100: (orange:1.5), (vibrant:1.8)
        200: (turquoise:1.5), (calm:1.8)
        300: (magenta:1.5), (energetic:1.8)
        400:(lime:1.5), (mellow:1.8)
        500:(black:1.5), (slow:1.8)
2023-11-16 22:59:41,771 ERROR: minds_eye_prompt.py failed.
2023-11-16 22:59:41,771 ERROR: Error: Traceback (most recent call last):
  File "D:\sentiMation\generators\minds_eye\minds_eye_prompt.py", line 56, in <module>
    file.write(chosen_prompt)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 43: character maps to <undefined>

2023-11-16 23:06:27,022 - INFO - Chosen prompt: (human eye:1.7), Abstract hallucinatory art in the style of James R. Eads, fluid and morphing, vibrant, 8k, high dynamic range
        0: (purple:1.5), (mellow:1.8)
        100: (orange:1.5), (vibrant:1.8)
        200: (turquoise:1.5), (calm:1.8)
        300: (magenta:1.5), (energetic:1.8)
        400:(lime:1.5), (mellow:1.8)
        500:(black:1.5), (slow:1.8)
2023-11-16 23:06:27,028 INFO: minds_eye_prompt.py finished successfully.
2023-11-16 23:06:27,028 INFO: Output: 
2023-11-16 23:06:27,200 INFO: Chosen prompt: (human eye:1.7), Abstract hallucinatory art in the style of James R. Eads, fluid and morphing, vibrant, 8k, high dynamic range
        0: (purple:1.5), (mellow:1.8)
        100: (orange:1.5), (vibrant:1.8)
        200: (turquoise:1.5), (calm:1.8)
        300: (magenta:1.5), (energetic:1.8)
        400:(lime:1.5), (mellow:1.8)
        500:(black:1.5), (slow:1.8)
2023-11-16 23:09:15,341 ERROR: minds_eye_generator.py failed.
2023-11-16 23:09:15,341 ERROR: Error: Traceback (most recent call last):
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\sentiMation\generators\minds_eye\minds_eye_generator.py", line 60, in <module>
    response = requests.post(api_url, headers=headers, json=json_payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Josh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

2023-11-16 23:12:14,273 - INFO - Chosen prompt: (human eye:1.3), Psychedelic patterns in Amanda Sage's visionary style, full of symbolism, deep colors, high contrast, 8k
        0: (purple:1.5), (mellow:1.8)
        100: (orange:1.5), (vibrant:1.8)
        200: (turquoise:1.5), (calm:1.8)
        300: (magenta:1.5), (energetic:1.8)
        400:(lime:1.5), (mellow:1.8)
        500:(black:1.5), (slow:1.8)
2023-11-16 23:12:14,279 INFO: minds_eye_prompt.py finished successfully.
2023-11-16 23:12:14,279 INFO: Output: 
2023-11-16 23:12:14,447 INFO: Chosen prompt: (human eye:1.3), Psychedelic patterns in Amanda Sage's visionary style, full of symbolism, deep colors, high contrast, 8k
        0: (purple:1.5), (mellow:1.8)
        100: (orange:1.5), (vibrant:1.8)
        200: (turquoise:1.5), (calm:1.8)
        300: (magenta:1.5), (energetic:1.8)
        400:(lime:1.5), (mellow:1.8)
        500:(black:1.5), (slow:1.8)
2023-11-16 23:13:23,848 INFO: API call successful. Status Code: 200
2023-11-16 23:13:23,867 INFO: minds_eye_generator.py finished successfully.
2023-11-16 23:13:23,867 INFO: Output: 
2023-11-16 23:14:30,808 - INFO - Chosen prompt: (human eye:1.3), Psychedelic patterns in Amanda Sage's visionary style, full of symbolism, deep colors, high contrast, 8k
        0: (purple:1.5), (mellow:1.8)
        100: (orange:1.5), (vibrant:1.8)
        200: (turquoise:1.5), (calm:1.8)
        300: (magenta:1.5), (energetic:1.8)
        400:(lime:1.5), (mellow:1.8)
        500:(black:1.5), (slow:1.8)
2023-11-16 23:14:30,814 INFO: minds_eye_prompt.py finished successfully.
2023-11-16 23:14:30,814 INFO: Output: 
2023-11-16 23:14:30,978 INFO: Chosen prompt: (human eye:1.3), Psychedelic patterns in Amanda Sage's visionary style, full of symbolism, deep colors, high contrast, 8k
        0: (purple:1.5), (mellow:1.8)
        100: (orange:1.5), (vibrant:1.8)
        200: (turquoise:1.5), (calm:1.8)
        300: (magenta:1.5), (energetic:1.8)
        400:(lime:1.5), (mellow:1.8)
        500:(black:1.5), (slow:1.8)
2023-11-16 23:15:36,135 INFO: API call successful. Status Code: 200
2023-11-16 23:15:36,156 INFO: minds_eye_generator.py finished successfully.
2023-11-16 23:15:36,156 INFO: Output: 
2023-11-16 23:16:21,279 - INFO - Chosen prompt: \(human eye:1.7), Psychedelic landscape in Alex Grey's style, vibrant and transcendent, ultra-detailed, luminous colors, 8k resolution
        0: (purple:1.5), (mellow:1.8)
        1: (orange:1.5), (vibrant:1.8)
        3: (turquoise:1.5), (calm:1.8)
        5: (magenta:1.5), (energetic:1.8)
        10:(lime:1.5), (mellow:1.8)
        13:(black:1.5), (slow:1.8)
2023-11-16 23:16:21,284 INFO: minds_eye_prompt.py finished successfully.
2023-11-16 23:16:21,285 INFO: Output: 
2023-11-16 23:16:21,454 INFO: Chosen prompt: \(human eye:1.7), Psychedelic landscape in Alex Grey's style, vibrant and transcendent, ultra-detailed, luminous colors, 8k resolution
        0: (purple:1.5), (mellow:1.8)
        1: (orange:1.5), (vibrant:1.8)
        3: (turquoise:1.5), (calm:1.8)
        5: (magenta:1.5), (energetic:1.8)
        10:(lime:1.5), (mellow:1.8)
        13:(black:1.5), (slow:1.8)
2023-11-16 23:17:29,252 INFO: API call successful. Status Code: 200
2023-11-16 23:17:29,275 INFO: minds_eye_generator.py finished successfully.
2023-11-16 23:17:29,275 INFO: Output: 
2023-11-16 23:18:18,304 - INFO - Chosen prompt: (human eye:1.7),Surreal visuals in the style of Salvador Dali, transformed into psychedelic art, ultra-sharp, dreamlike, 8k
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
4: (turquoise:1.5), (calm:1.8)
8: (magenta:1.5), (energetic:1.8)
12:(lime:1.5), (mellow:1.8)
14:(black:1.5), (slow:1.8)
2023-11-16 23:18:18,311 INFO: minds_eye_prompt.py finished successfully.
2023-11-16 23:18:18,311 INFO: Output: 
2023-11-16 23:18:18,503 INFO: Chosen prompt: (human eye:1.7),Surreal visuals in the style of Salvador Dali, transformed into psychedelic art, ultra-sharp, dreamlike, 8k
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
4: (turquoise:1.5), (calm:1.8)
8: (magenta:1.5), (energetic:1.8)
12:(lime:1.5), (mellow:1.8)
14:(black:1.5), (slow:1.8)
2023-11-16 23:19:29,989 INFO: API call successful. Status Code: 200
2023-11-16 23:19:30,015 INFO: minds_eye_generator.py finished successfully.
2023-11-16 23:19:30,016 INFO: Output: 
2023-11-16 23:22:17,422 - INFO - Chosen prompt: 
\(human eye), Phantasmagoric scenes in the style of Zdzis\u0142aw Beksi\u0144ski, psychedelic twist, dark yet vibrant, ultra HD
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
4: (turquoise:1.5), (calm:1.8)
8: (magenta:1.5), (energetic:1.8)
12:(lime:1.5), (mellow:1.8)
14:(black:1.5), (slow:1.8)
2023-11-16 23:22:17,428 ERROR: minds_eye_prompt.py failed.
2023-11-16 23:22:17,428 ERROR: Error: Traceback (most recent call last):
  File "D:\sentiMation\generators\minds_eye\minds_eye_prompt.py", line 62, in <module>
    file.write(chosen_prompt)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 59: character maps to <undefined>

2023-11-16 23:23:33,981 - INFO - Chosen prompt: (human eye), Abstract hallucinatory art in the style of James R. Eads, fluid and morphing, vibrant, 8k, high dynamic range
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
4: (turquoise:1.5), (calm:1.8)
8: (magenta:1.5), (energetic:1.8)
12:(lime:1.5), (mellow:1.8)
14:(black:1.5), (slow:1.8)
2023-11-16 23:23:33,987 INFO: minds_eye_prompt.py finished successfully.
2023-11-16 23:23:33,987 INFO: Output: 
2023-11-16 23:23:34,154 INFO: Chosen prompt: (human eye), Abstract hallucinatory art in the style of James R. Eads, fluid and morphing, vibrant, 8k, high dynamic range
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
4: (turquoise:1.5), (calm:1.8)
8: (magenta:1.5), (energetic:1.8)
12:(lime:1.5), (mellow:1.8)
14:(black:1.5), (slow:1.8)
2023-11-16 23:24:38,560 INFO: API call successful. Status Code: 200
2023-11-16 23:24:38,580 INFO: minds_eye_generator.py finished successfully.
2023-11-16 23:24:38,580 INFO: Output: 
2023-11-16 23:34:48,943 - INFO - Chosen prompt: 
\(human eye), Phantasmagoric scenes in the style of Zdzis\u0142aw Beksi\u0144ski, psychedelic twist, dark yet vibrant, ultra HD
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
4: (turquoise:1.5), (calm:1.8)
8: (magenta:1.5), (energetic:1.8)
12:(lime:1.5), (mellow:1.8)
14:(black:1.5), (slow:1.8)
2023-11-16 23:34:48,949 ERROR: minds_eye_prompt.py failed.
2023-11-16 23:34:48,949 ERROR: Error: Traceback (most recent call last):
  File "D:\sentiMation\generators\minds_eye\minds_eye_prompt.py", line 62, in <module>
    file.write(chosen_prompt)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 59: character maps to <undefined>

2023-11-16 23:35:49,576 - INFO - Chosen prompt: (human eye), Psychedelic patterns in Amanda Sage's visionary style, full of symbolism, deep colors, high contrast, 8k
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
4: (turquoise:1.5), (calm:1.8)
8: (magenta:1.5), (energetic:1.8)
12:(lime:1.5), (mellow:1.8)
14:(black:1.5), (slow:1.8)
2023-11-16 23:35:49,582 INFO: minds_eye_prompt.py finished successfully.
2023-11-16 23:35:49,582 INFO: Output: 
2023-11-16 23:35:49,745 INFO: Chosen prompt: (human eye), Psychedelic patterns in Amanda Sage's visionary style, full of symbolism, deep colors, high contrast, 8k
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
4: (turquoise:1.5), (calm:1.8)
8: (magenta:1.5), (energetic:1.8)
12:(lime:1.5), (mellow:1.8)
14:(black:1.5), (slow:1.8)
2023-11-16 23:39:12,562 INFO: API call successful. Status Code: 200
2023-11-16 23:39:12,583 INFO: minds_eye_generator.py finished successfully.
2023-11-16 23:39:12,583 INFO: Output: 
2023-11-16 23:41:37,885 - INFO - Chosen prompt: (human eye), Psychedelic landscape in Alex Grey's style, vibrant and transcendent, ultra-detailed, luminous colors, 8k resolution
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
3: (turquoise:1.5), (calm:1.8)
5: (magenta:1.5), (energetic:1.8)
10:(lime:1.5), (mellow:1.8)
13:(black:1.5), (slow:1.8)
2023-11-16 23:41:37,893 INFO: minds_eye_prompt.py finished successfully.
2023-11-16 23:41:37,893 INFO: Output: 
2023-11-16 23:41:38,064 INFO: Chosen prompt: (human eye), Psychedelic landscape in Alex Grey's style, vibrant and transcendent, ultra-detailed, luminous colors, 8k resolution
0: (purple:1.5), (mellow:1.8)
1: (orange:1.5), (vibrant:1.8)
3: (turquoise:1.5), (calm:1.8)
5: (magenta:1.5), (energetic:1.8)
10:(lime:1.5), (mellow:1.8)
13:(black:1.5), (slow:1.8)
2023-11-16 23:44:53,762 INFO: API call successful. Status Code: 200
2023-11-16 23:44:53,787 INFO: minds_eye_generator.py finished successfully.
2023-11-16 23:44:53,788 INFO: Output: 
